const THEMES = [
  {
    name: "vs",
    label: "VS",
    base: "vs",
    colors: {},
    rules: [],
  },
  {
    name: "vs-dark",
    label: "VS Dark",
    base: "vs-dark",
    colors: {},
    rules: [],
  },
  {
    name: "github-light",
    label: "GitHub Light",
    base: "vs",
    colors: {
      "editor.background": "#f6f8fa",
      "editor.foreground": "#1f2328",
      "editor.lineHighlightBackground": "#e1e4e8",
      "editor.selectionBackground": "#c8c8fa",
      "editorCursor.foreground": "#1f2328",
      "editorLineNumber.foreground": "#8b949e",
      "editorLineNumber.activeForeground": "#1f2328",
      "editorBracketMatch.background": "#e1e4e8",
      "editorBracketMatch.border": "#c8c8fa",
      "scrollbar.shadow": "#f6f8fa",
      "scrollbarSlider.background": "#d0d7de",
      "scrollbarSlider.hoverBackground": "#afb8c1",
      "scrollbarSlider.activeBackground": "#8b949e",
      "minimap.background": "#f6f8fa",
      "editorGutter.background": "#f6f8fa",
      "editorWidget.background": "#f6f8fa",
    },
    rules: [
      { token: "keyword", foreground: "cf222e" },
      { token: "string", foreground: "0a3069" },
      { token: "string.sql", foreground: "0a3069" },
      { token: "number", foreground: "0550ae" },
      { token: "comment", foreground: "8b949e" },
      { token: "type", foreground: "953800" },
      { token: "function", foreground: "8250df" },
      { token: "variable", foreground: "953800" },
      { token: "namespace", foreground: "cf222e" },
      { token: "property", foreground: "0550ae" },
      { token: "operator", foreground: "953800" },
      { token: "delimiter", foreground: "1f2328" },
      { token: "predefined", foreground: "8250df" },
    ],
  },
  {
    name: "github-dark",
    label: "GitHub Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#151b23",
      "editor.foreground": "#e6edf3",
      "editor.lineHighlightBackground": "#21262d",
      "editor.selectionBackground": "#3a404a",
      "editorCursor.foreground": "#e6edf3",
      "editorLineNumber.foreground": "#636e7b",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editorBracketMatch.background": "#2ea043",
      "editorBracketMatch.border": "#2ea043",
      "scrollbar.shadow": "#151b23",
      "scrollbarSlider.background": "#6e768166",
      "scrollbarSlider.hoverBackground": "#6e7681",
      "scrollbarSlider.activeBackground": "#6e7681",
      "minimap.background": "#151b23",
      "editorGutter.background": "#151b23",
      "editorWidget.background": "#21262d",
    },
    rules: [
      { token: "keyword", foreground: "ff7b72" },
      { token: "string", foreground: "a5d6ff" },
      { token: "string.sql", foreground: "a5d6ff" },
      { token: "number", foreground: "79c0ff" },
      { token: "comment", foreground: "8b949e" },
      { token: "type", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
      { token: "variable", foreground: "ffa657" },
      { token: "namespace", foreground: "ff7b72" },
      { token: "property", foreground: "79c0ff" },
      { token: "operator", foreground: "ffb347" },
      { token: "delimiter", foreground: "e6edf3" },
      { token: "predefined", foreground: "d2a8ff" },
    ],
  },
  {
    name: "solarized-light",
    label: "Solarized Light",
    base: "vs",
    colors: {
      "editor.background": "#fdf6e3",
      "editor.foreground": "#657b83",
      "editor.lineHighlightBackground": "#eee8d5",
      "editor.selectionBackground": "#839496",
      "editorCursor.foreground": "#657b83",
      "editorLineNumber.foreground": "#93a1a1",
      "editorLineNumber.activeForeground": "#657b83",
      "editorBracketMatch.background": "#eee8d5",
      "editorBracketMatch.border": "#859900",
      "scrollbar.shadow": "#fdf6e3",
      "scrollbarSlider.background": "#93a1a1",
      "scrollbarSlider.hoverBackground": "#839496",
      "scrollbarSlider.activeBackground": "#657b83",
      "minimap.background": "#fdf6e3",
      "editorGutter.background": "#fdf6e3",
      "editorWidget.background": "#fdf6e3",
    },
    rules: [
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "string.sql", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "comment", foreground: "93a1a1" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
      { token: "variable", foreground: "b58900" },
      { token: "namespace", foreground: "859900" },
      { token: "property", foreground: "268bd2" },
      { token: "operator", foreground: "586e75" },
      { token: "delimiter", foreground: "657b83" },
      { token: "predefined", foreground: "268bd2" },
    ],
  },
  {
    name: "solarized-dark",
    label: "Solarized Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#002b36",
      "editor.foreground": "#839496",
      "editor.lineHighlightBackground": "#073642",
      "editor.selectionBackground": "#586e75",
      "editorCursor.foreground": "#839496",
      "editorLineNumber.foreground": "#586e75",
      "editorLineNumber.activeForeground": "#839496",
      "editorBracketMatch.background": "#073642",
      "editorBracketMatch.border": "#859900",
      "scrollbar.shadow": "#002b36",
      "scrollbarSlider.background": "#586e75",
      "scrollbarSlider.hoverBackground": "#657b83",
      "scrollbarSlider.activeBackground": "#839496",
      "minimap.background": "#002b36",
      "editorGutter.background": "#002b36",
      "editorWidget.background": "#073642",
    },
    rules: [
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "string.sql", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "comment", foreground: "586e75" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
      { token: "variable", foreground: "b58900" },
      { token: "namespace", foreground: "859900" },
      { token: "property", foreground: "268bd2" },
      { token: "operator", foreground: "93a1a1" },
      { token: "delimiter", foreground: "839496" },
      { token: "predefined", foreground: "268bd2" },
    ],
  },
  {
    name: "one-light",
    label: "One Light",
    base: "vs",
    colors: {
      "editor.background": "#fafafa",
      "editor.foreground": "#383a42",
      "editor.lineHighlightBackground": "#eaeaeb",
      "editor.selectionBackground": "#e5e5e6",
      "editorCursor.foreground": "#526fff",
      "editorLineNumber.foreground": "#d0d0d0",
      "editorLineNumber.activeForeground": "#383a42",
      "editorBracketMatch.background": "#eaeaeb",
      "editorBracketMatch.border": "#383a42",
      "scrollbar.shadow": "#fafafa",
      "scrollbarSlider.background": "#d0d0d0",
      "scrollbarSlider.hoverBackground": "#b0b0b0",
      "scrollbarSlider.activeBackground": "#909090",
      "minimap.background": "#fafafa",
      "editorGutter.background": "#fafafa",
      "editorWidget.background": "#fafafa",
    },
    rules: [
      { token: "keyword", foreground: "a626a4" },
      { token: "string", foreground: "50a14f" },
      { token: "string.sql", foreground: "50a14f" },
      { token: "number", foreground: "986801" },
      { token: "comment", foreground: "a0a1a7" },
      { token: "type", foreground: "e45649" },
      { token: "function", foreground: "4078f2" },
      { token: "variable", foreground: "e45649" },
      { token: "namespace", foreground: "a626a4" },
      { token: "property", foreground: "4078f2" },
      { token: "operator", foreground: "383a42" },
      { token: "delimiter", foreground: "383a42" },
      { token: "predefined", foreground: "4078f2" },
    ],
  },
  {
    name: "one-dark",
    label: "One Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      "editor.lineHighlightBackground": "#2c323c",
      "editor.selectionBackground": "#3e4451",
      "editorCursor.foreground": "#528bff",
      "editorLineNumber.foreground": "#4b5263",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorBracketMatch.background": "#2c323c",
      "editorBracketMatch.border": "#528bff",
      "scrollbar.shadow": "#282c34",
      "scrollbarSlider.background": "#4b5263",
      "scrollbarSlider.hoverBackground": "#5c6370",
      "scrollbarSlider.activeBackground": "#6e7681",
      "minimap.background": "#282c34",
      "editorGutter.background": "#282c34",
      "editorWidget.background": "#2c323c",
    },
    rules: [
      { token: "keyword", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "string.sql", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "comment", foreground: "5c6370" },
      { token: "type", foreground: "e5c07b" },
      { token: "function", foreground: "61afef" },
      { token: "variable", foreground: "e5c07b" },
      { token: "namespace", foreground: "c678dd" },
      { token: "property", foreground: "61afef" },
      { token: "operator", foreground: "abb2bf" },
      { token: "delimiter", foreground: "abb2bf" },
      { token: "predefined", foreground: "61afef" },
    ],
  },
  {
    name: "gruvbox-light",
    label: "Gruvbox Light",
    base: "vs",
    colors: {
      "editor.background": "#fbf1c7",
      "editor.foreground": "#3c3836",
      "editor.lineHighlightBackground": "#ebdbb2",
      "editor.selectionBackground": "#d5c4a1",
      "editorCursor.foreground": "#3c3836",
      "editorLineNumber.foreground": "#bdae93",
      "editorLineNumber.activeForeground": "#3c3836",
      "editorBracketMatch.background": "#ebdbb2",
      "editorBracketMatch.border": "#689d6a",
      "scrollbar.shadow": "#fbf1c7",
      "scrollbarSlider.background": "#bdae93",
      "scrollbarSlider.hoverBackground": "#a89984",
      "scrollbarSlider.activeBackground": "#928374",
      "minimap.background": "#fbf1c7",
      "editorGutter.background": "#fbf1c7",
      "editorWidget.background": "#fbf1c7",
    },
    rules: [
      { token: "keyword", foreground: "9d0006" },
      { token: "string", foreground: "79740e" },
      { token: "string.sql", foreground: "79740e" },
      { token: "number", foreground: "8f3f71" },
      { token: "comment", foreground: "bdae93" },
      { token: "type", foreground: "b57614" },
      { token: "function", foreground: "076678" },
      { token: "variable", foreground: "b57614" },
      { token: "namespace", foreground: "9d0006" },
      { token: "property", foreground: "076678" },
      { token: "operator", foreground: "3c3836" },
      { token: "delimiter", foreground: "3c3836" },
      { token: "predefined", foreground: "076678" },
    ],
  },
  {
    name: "gruvbox-dark",
    label: "Gruvbox Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#282828",
      "editor.foreground": "#ebdbb2",
      "editor.lineHighlightBackground": "#3c3836",
      "editor.selectionBackground": "#504945",
      "editorCursor.foreground": "#ebdbb2",
      "editorLineNumber.foreground": "#665c54",
      "editorLineNumber.activeForeground": "#ebdbb2",
      "editorBracketMatch.background": "#3c3836",
      "editorBracketMatch.border": "#689d6a",
      "scrollbar.shadow": "#282828",
      "scrollbarSlider.background": "#665c54",
      "scrollbarSlider.hoverBackground": "#7c6f64",
      "scrollbarSlider.activeBackground": "#928374",
      "minimap.background": "#282828",
      "editorGutter.background": "#282828",
      "editorWidget.background": "#3c3836",
    },
    rules: [
      { token: "keyword", foreground: "fb4934" },
      { token: "string", foreground: "b8bb26" },
      { token: "string.sql", foreground: "b8bb26" },
      { token: "number", foreground: "d3869b" },
      { token: "comment", foreground: "665c54" },
      { token: "type", foreground: "fabd2f" },
      { token: "function", foreground: "83a598" },
      { token: "variable", foreground: "fabd2f" },
      { token: "namespace", foreground: "fb4934" },
      { token: "property", foreground: "83a598" },
      { token: "operator", foreground: "ebdbb2" },
      { token: "delimiter", foreground: "ebdbb2" },
      { token: "predefined", foreground: "83a598" },
    ],
  },
  {
    name: "catppuccin-light",
    label: "Catppuccin Latte",
    base: "vs",
    colors: {
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "editor.lineHighlightBackground": "#e6e9ef",
      "editor.selectionBackground": "#ccd0da",
      "editorCursor.foreground": "#dc8a78",
      "editorLineNumber.foreground": "#bcc0cc",
      "editorLineNumber.activeForeground": "#4c4f69",
      "editorBracketMatch.background": "#e6e9ef",
      "editorBracketMatch.border": "#40a02b",
      "scrollbar.shadow": "#eff1f5",
      "scrollbarSlider.background": "#bcc0cc",
      "scrollbarSlider.hoverBackground": "#9ca0b0",
      "scrollbarSlider.activeBackground": "#7c7f93",
      "minimap.background": "#eff1f5",
      "editorGutter.background": "#eff1f5",
      "editorWidget.background": "#eff1f5",
    },
    rules: [
      { token: "keyword", foreground: "8839ef" },
      { token: "string", foreground: "40a02b" },
      { token: "string.sql", foreground: "40a02b" },
      { token: "number", foreground: "fe640b" },
      { token: "comment", foreground: "bcc0cc" },
      { token: "type", foreground: "df8e1d" },
      { token: "function", foreground: "1e66f5" },
      { token: "variable", foreground: "df8e1d" },
      { token: "namespace", foreground: "8839ef" },
      { token: "property", foreground: "1e66f5" },
      { token: "operator", foreground: "4c4f69" },
      { token: "delimiter", foreground: "4c4f69" },
      { token: "predefined", foreground: "1e66f5" },
    ],
  },
  {
    name: "catppuccin-dark",
    label: "Catppuccin Mocha",
    base: "vs-dark",
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#313244",
      "editor.selectionBackground": "#45475a",
      "editorCursor.foreground": "#f5e0dc",
      "editorLineNumber.foreground": "#585b70",
      "editorLineNumber.activeForeground": "#cdd6f4",
      "editorBracketMatch.background": "#313244",
      "editorBracketMatch.border": "#a6e3a1",
      "scrollbar.shadow": "#1e1e2e",
      "scrollbarSlider.background": "#585b70",
      "scrollbarSlider.hoverBackground": "#6c7086",
      "scrollbarSlider.activeBackground": "#7f849c",
      "minimap.background": "#1e1e2e",
      "editorGutter.background": "#1e1e2e",
      "editorWidget.background": "#313244",
    },
    rules: [
      { token: "keyword", foreground: "cba6f7" },
      { token: "string", foreground: "a6e3a1" },
      { token: "string.sql", foreground: "a6e3a1" },
      { token: "number", foreground: "fab387" },
      { token: "comment", foreground: "585b70" },
      { token: "type", foreground: "f9e2af" },
      { token: "function", foreground: "89b4fa" },
      { token: "variable", foreground: "f9e2af" },
      { token: "namespace", foreground: "cba6f7" },
      { token: "property", foreground: "89b4fa" },
      { token: "operator", foreground: "cdd6f4" },
      { token: "delimiter", foreground: "cdd6f4" },
      { token: "predefined", foreground: "89b4fa" },
    ],
  },
  {
    name: "monokai",
    label: "Monokai",
    base: "vs-dark",
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#3e3d32",
      "editor.selectionBackground": "#49483e",
      "editorCursor.foreground": "#f8f8f0",
      "editorLineNumber.foreground": "#75715e",
      "editorLineNumber.activeForeground": "#f8f8f2",
      "editorBracketMatch.background": "#3e3d32",
      "editorBracketMatch.border": "#a6e22e",
      "scrollbar.shadow": "#272822",
      "scrollbarSlider.background": "#75715e",
      "scrollbarSlider.hoverBackground": "#90908a",
      "scrollbarSlider.activeBackground": "#a6a69e",
      "minimap.background": "#272822",
      "editorGutter.background": "#272822",
      "editorWidget.background": "#3e3d32",
    },
    rules: [
      { token: "keyword", foreground: "f92672" },
      { token: "string", foreground: "e6db74" },
      { token: "string.sql", foreground: "e6db74" },
      { token: "number", foreground: "ae81ff" },
      { token: "comment", foreground: "75715e" },
      { token: "type", foreground: "a6e22e" },
      { token: "function", foreground: "a6e22e" },
      { token: "variable", foreground: "f8f8f2" },
      { token: "namespace", foreground: "f92672" },
      { token: "property", foreground: "66d9ef" },
      { token: "operator", foreground: "f92672" },
      { token: "delimiter", foreground: "f8f8f2" },
      { token: "predefined", foreground: "a6e22e" },
    ],
  },
];

export function registerAllMonacoThemes(monaco) {
  THEMES.forEach(function (t) {
    monaco.editor.defineTheme(t.name, {
      base: t.base,
      inherit: true,
      rules: t.rules,
      colors: t.colors,
    });
  });
}

export function getMonacoSyntaxRules(themeName) {
  var theme = THEMES.find(function (t) {
    return t.name === themeName;
  });
  return theme ? theme.rules : [];
}

export var monacoThemeList = THEMES.map(function (t) {
  return { label: t.label, value: t.name };
});

/**
 * Map tra màu bg/fg của từng Monaco theme.
 * Dùng để set CSS vars --td-monaco-footer-bg / --td-monaco-footer-fg lên :root bằng JS.
 */
export var monacoThemeColorMap = THEMES.reduce(function (map, t) {
  map[t.name] = {
    bg:
      t.colors["editor.background"] ||
      (t.base === "vs" ? "#ffffff" : "#1e1e1e"),
    fg:
      t.colors["editor.foreground"] ||
      (t.base === "vs" ? "#000000" : "#d4d4d4"),
  };
  return map;
}, {});
