const THEMES = [
  {
    name: "vs",
    label: "VS",
    base: "vs",
    colors: {},
    rules: [],
    appVars: {
      "--bg-main-color": "#ffffff",
      "--bg-layer-color": "#f3f4f6",
      "--bg-hover-color": "#00000010",
      "--bg-active-color": "rgb(202, 212, 203)",
      "--bg-focus-color": "#f8f1f7",
      "--bg-thirt-color": "#f6f6f7",
      "--text-color": "#4b5563",
      "--text-primary-color": "rgb(0, 0, 0)",
      "--text-secondary-color": "rgb(93, 93, 93)",
      "--text-tertiary-color": "rgb(44, 34, 34)",
      "--border-color": "#e6e7eb",
      "--border-hard-color": "rgb(40, 38, 38)",
      "--border-component-style": "1px solid #e6e7eb7d",
      "--focus-color": "#000000",
      "--btn-color": "#343434",
      "--btn-secondary-color": "#f1f1f1",
      "--btn-secondary-text-color": "#476582",
      "--btn-secondary-focus-color": "#e5e5e5",
      "--btn-primary-bg": "#343434",
      "--selected-item-text-color": "var(--btn-secondary-color)",
      "--btn-secondary-bg": "var(--btn-secondary-color)",
      "--btn-secondary-hover-bg": "var(--btn-secondary-focus-color)",
      "--btn-secondary-hover-border": "transparent",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#54545470",
      "--scroll-thumb-hover-color": "#545454",
      "--bg-tooltip-color": "#f3f3f3",
      "--bg-tooltip-border-color": "#c8c8c8",
      "--tooltip-color": "#616161",
      "--trail-cursor-color": "#000000",
      "--checkbox-thumb-active-color": "#000000",
      "--td-slide-bg": "var(--focus-color)",
      "--td-monaco-footer-bg": "#ffffff",
      "--td-monaco-footer-fg": "#000000",
      "--td-monaco-text-active": "#000000",
      "--td-monaco-text-inactive": "#8b949e",
      "--text-color-secondary": "rgb(93, 93, 93)",
      "--bg-secondary": "#f3f4f6",
      "--bg-color": "#ffffff",
    },
  },
  {
    name: "vs-dark",
    label: "VS Dark",
    base: "vs-dark",
    colors: {},
    rules: [],
    appVars: {
      "--bg-main-color": "#000000",
      "--bg-layer-color": "rgb(35, 35, 35)",
      "--bg-hover-color": "rgb(174, 37, 37)",
      "--bg-active-color": "rgb(126, 126, 126)",
      "--bg-focus-color": "#928990",
      "--bg-thirt-color": "#252525",
      "--text-color": "#e5e5e5",
      "--text-primary-color": "rgb(226, 227, 231)",
      "--text-secondary-color": "#6a707e",
      "--text-tertiary-color": "rgb(217, 217, 217)",
      "--border-color": "#3c3d3d",
      "--border-hard-color": "rgb(224, 224, 224)",
      "--border-component-style": "1px solid #666666",
      "--focus-color": "#515151",
      "--btn-color": "#5f5f5f",
      "--btn-secondary-color": "#353434",
      "--btn-secondary-text-color": "#8f95a1",
      "--btn-secondary-focus-color": "#545454",
      "--btn-primary-bg": "var(--bg-hover-color)",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#303130",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#54545470",
      "--scroll-thumb-hover-color": "#545454",
      "--bg-tooltip-color": "#252526",
      "--bg-tooltip-border-color": "#454545",
      "--tooltip-color": "#cccccc",
      "--trail-cursor-color": "#ddfa42",
      "--checkbox-thumb-active-color": "rgb(174, 37, 37)",
      "--td-slide-bg": "var(--bg-hover-color)",
      "--td-monaco-footer-bg": "#1e1e1e",
      "--td-monaco-footer-fg": "#d4d4d4",
      "--td-monaco-text-active": "#d4d4d4",
      "--td-monaco-text-inactive": "#636e7b",
      "--text-color-secondary": "#6a707e",
      "--bg-secondary": "rgb(35, 35, 35)",
      "--bg-color": "#000000",
    },
  },
  {
    name: "github-light",
    label: "GitHub Light",
    base: "vs",
    colors: {
      "editor.background": "#f6f8fa",
      "editor.foreground": "#1f2328",
      "editor.lineHighlightBackground": "#e1e4e8",
      "editor.selectionBackground": "#c8c8fa",
      "editorCursor.foreground": "#1f2328",
      "editorLineNumber.foreground": "#8b949e",
      "editorLineNumber.activeForeground": "#1f2328",
      "editorBracketMatch.background": "#e1e4e8",
      "editorBracketMatch.border": "#c8c8fa",
      "scrollbar.shadow": "#f6f8fa",
      "scrollbarSlider.background": "#d0d7de",
      "scrollbarSlider.hoverBackground": "#afb8c1",
      "scrollbarSlider.activeBackground": "#8b949e",
      "minimap.background": "#f6f8fa",
      "editorGutter.background": "#f6f8fa",
      "editorWidget.background": "#f6f8fa",
    },
    rules: [
      { token: "keyword", foreground: "cf222e" },
      { token: "string", foreground: "0a3069" },
      { token: "string.sql", foreground: "0a3069" },
      { token: "number", foreground: "0550ae" },
      { token: "comment", foreground: "8b949e" },
      { token: "type", foreground: "953800" },
      { token: "function", foreground: "8250df" },
      { token: "variable", foreground: "953800" },
      { token: "namespace", foreground: "cf222e" },
      { token: "property", foreground: "0550ae" },
      { token: "operator", foreground: "953800" },
      { token: "delimiter", foreground: "1f2328" },
      { token: "predefined", foreground: "8250df" },
    ],
    appVars: {
      "--bg-main-color": "#f6f8fa",
      "--bg-layer-color": "#e1e4e8",
      "--bg-hover-color": "#0550ae20",
      "--bg-active-color": "#c8c8fa",
      "--bg-focus-color": "#c8c8fa",
      "--bg-thirt-color": "#eaeef2",
      "--text-color": "#1f2328",
      "--text-primary-color": "#1f2328",
      "--text-secondary-color": "#8b949e",
      "--text-tertiary-color": "#24292f",
      "--border-color": "#d0d7de",
      "--border-hard-color": "#1f2328",
      "--border-component-style": "1px solid #d0d7de",
      "--focus-color": "#0550ae",
      "--btn-color": "#1f2328",
      "--btn-secondary-color": "#e8eaed",
      "--btn-secondary-text-color": "#0550ae",
      "--btn-secondary-focus-color": "#e1e4e8",
      "--btn-primary-bg": "#0550ae",
      "--selected-item-text-color": "var(--btn-secondary-color)",
      "--btn-secondary-bg": "var(--btn-secondary-color)",
      "--btn-secondary-hover-bg": "var(--btn-secondary-focus-color)",
      "--btn-secondary-hover-border": "transparent",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#d0d7de",
      "--scroll-thumb-hover-color": "#afb8c1",
      "--bg-tooltip-color": "#f6f8fa",
      "--bg-tooltip-border-color": "#d0d7de",
      "--tooltip-color": "#57606a",
      "--trail-cursor-color": "#1f2328",
      "--checkbox-thumb-active-color": "#0550ae",
      "--td-slide-bg": "#0550ae",
      "--td-monaco-footer-bg": "#f6f8fa",
      "--td-monaco-footer-fg": "#1f2328",
      "--td-monaco-text-active": "#1f2328",
      "--td-monaco-text-inactive": "#8b949e",
      "--text-color-secondary": "#8b949e",
      "--bg-secondary": "#e1e4e8",
      "--bg-color": "#f6f8fa",
    },
  },
  {
    name: "github-dark",
    label: "GitHub Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#151b23",
      "editor.foreground": "#e6edf3",
      "editor.lineHighlightBackground": "#21262d",
      "editor.selectionBackground": "#3a404a",
      "editorCursor.foreground": "#e6edf3",
      "editorLineNumber.foreground": "#636e7b",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editorBracketMatch.background": "#2ea043",
      "editorBracketMatch.border": "#2ea043",
      "scrollbar.shadow": "#151b23",
      "scrollbarSlider.background": "#6e768166",
      "scrollbarSlider.hoverBackground": "#6e7681",
      "scrollbarSlider.activeBackground": "#6e7681",
      "minimap.background": "#151b23",
      "editorGutter.background": "#151b23",
      "editorWidget.background": "#21262d",
    },
    rules: [
      { token: "keyword", foreground: "ff7b72" },
      { token: "string", foreground: "a5d6ff" },
      { token: "string.sql", foreground: "a5d6ff" },
      { token: "number", foreground: "79c0ff" },
      { token: "comment", foreground: "8b949e" },
      { token: "type", foreground: "ffa657" },
      { token: "function", foreground: "d2a8ff" },
      { token: "variable", foreground: "ffa657" },
      { token: "namespace", foreground: "ff7b72" },
      { token: "property", foreground: "79c0ff" },
      { token: "operator", foreground: "ffb347" },
      { token: "delimiter", foreground: "e6edf3" },
      { token: "predefined", foreground: "d2a8ff" },
    ],
    appVars: {
      "--bg-main-color": "#0d1117",
      "--bg-layer-color": "#161b22",
      "--bg-hover-color": "#58a6ff22",
      "--bg-active-color": "#1f6feb33",
      "--bg-focus-color": "#1f6feb55",
      "--bg-thirt-color": "#21262d",
      "--text-color": "#e6edf3",
      "--text-primary-color": "#e6edf3",
      "--text-secondary-color": "#8b949e",
      "--text-tertiary-color": "#c9d1d9",
      "--border-color": "#30363d",
      "--border-hard-color": "#e6edf3",
      "--border-component-style": "1px solid #30363d",
      "--focus-color": "#58a6ff",
      "--btn-color": "#e6edf3",
      "--btn-secondary-color": "#21262d",
      "--btn-secondary-text-color": "#58a6ff",
      "--btn-secondary-focus-color": "#30363d",
      "--btn-primary-bg": "#58a6ff",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#30363d",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#6e768166",
      "--scroll-thumb-hover-color": "#6e7681",
      "--bg-tooltip-color": "#161b22",
      "--bg-tooltip-border-color": "#30363d",
      "--tooltip-color": "#8b949e",
      "--trail-cursor-color": "#58a6ff",
      "--checkbox-thumb-active-color": "#58a6ff",
      "--td-slide-bg": "#58a6ff",
      "--td-monaco-footer-bg": "#151b23",
      "--td-monaco-footer-fg": "#e6edf3",
      "--td-monaco-text-active": "#e6edf3",
      "--td-monaco-text-inactive": "#636e7b",
      "--text-color-secondary": "#8b949e",
      "--bg-secondary": "#161b22",
      "--bg-color": "#0d1117",
    },
  },
  {
    name: "solarized-light",
    label: "Solarized Light",
    base: "vs",
    colors: {
      "editor.background": "#fdf6e3",
      "editor.foreground": "#657b83",
      "editor.lineHighlightBackground": "#eee8d5",
      "editor.selectionBackground": "#839496",
      "editorCursor.foreground": "#657b83",
      "editorLineNumber.foreground": "#93a1a1",
      "editorLineNumber.activeForeground": "#657b83",
      "editorBracketMatch.background": "#eee8d5",
      "editorBracketMatch.border": "#859900",
      "scrollbar.shadow": "#fdf6e3",
      "scrollbarSlider.background": "#93a1a1",
      "scrollbarSlider.hoverBackground": "#839496",
      "scrollbarSlider.activeBackground": "#657b83",
      "minimap.background": "#fdf6e3",
      "editorGutter.background": "#fdf6e3",
      "editorWidget.background": "#fdf6e3",
    },
    rules: [
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "string.sql", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "comment", foreground: "93a1a1" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
      { token: "variable", foreground: "b58900" },
      { token: "namespace", foreground: "859900" },
      { token: "property", foreground: "268bd2" },
      { token: "operator", foreground: "586e75" },
      { token: "delimiter", foreground: "657b83" },
      { token: "predefined", foreground: "268bd2" },
    ],
    appVars: {
      "--bg-main-color": "#fdf6e3",
      "--bg-layer-color": "#eee8d5",
      "--bg-hover-color": "#268bd220",
      "--bg-active-color": "#93a1a1",
      "--bg-focus-color": "#eee8d5",
      "--bg-thirt-color": "#f5efdc",
      "--text-color": "#657b83",
      "--text-primary-color": "#586e75",
      "--text-secondary-color": "#93a1a1",
      "--text-tertiary-color": "#657b83",
      "--border-color": "#93a1a1",
      "--border-hard-color": "#586e75",
      "--border-component-style": "1px solid #93a1a17d",
      "--focus-color": "#268bd2",
      "--btn-color": "#586e75",
      "--btn-secondary-color": "#eee8d5",
      "--btn-secondary-text-color": "#268bd2",
      "--btn-secondary-focus-color": "#ddd6c1",
      "--btn-primary-bg": "#268bd2",
      "--selected-item-text-color": "var(--btn-secondary-color)",
      "--btn-secondary-bg": "var(--btn-secondary-color)",
      "--btn-secondary-hover-bg": "var(--btn-secondary-focus-color)",
      "--btn-secondary-hover-border": "transparent",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#93a1a170",
      "--scroll-thumb-hover-color": "#93a1a1",
      "--bg-tooltip-color": "#eee8d5",
      "--bg-tooltip-border-color": "#93a1a1",
      "--tooltip-color": "#657b83",
      "--trail-cursor-color": "#586e75",
      "--checkbox-thumb-active-color": "#268bd2",
      "--td-slide-bg": "#268bd2",
      "--td-monaco-footer-bg": "#fdf6e3",
      "--td-monaco-footer-fg": "#657b83",
      "--td-monaco-text-active": "#657b83",
      "--td-monaco-text-inactive": "#93a1a1",
      "--text-color-secondary": "#93a1a1",
      "--bg-secondary": "#eee8d5",
      "--bg-color": "#fdf6e3",
    },
  },
  {
    name: "solarized-dark",
    label: "Solarized Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#002b36",
      "editor.foreground": "#839496",
      "editor.lineHighlightBackground": "#073642",
      "editor.selectionBackground": "#586e75",
      "editorCursor.foreground": "#839496",
      "editorLineNumber.foreground": "#586e75",
      "editorLineNumber.activeForeground": "#839496",
      "editorBracketMatch.background": "#073642",
      "editorBracketMatch.border": "#859900",
      "scrollbar.shadow": "#002b36",
      "scrollbarSlider.background": "#586e75",
      "scrollbarSlider.hoverBackground": "#657b83",
      "scrollbarSlider.activeBackground": "#839496",
      "minimap.background": "#002b36",
      "editorGutter.background": "#002b36",
      "editorWidget.background": "#073642",
    },
    rules: [
      { token: "keyword", foreground: "859900" },
      { token: "string", foreground: "2aa198" },
      { token: "string.sql", foreground: "2aa198" },
      { token: "number", foreground: "d33682" },
      { token: "comment", foreground: "586e75" },
      { token: "type", foreground: "b58900" },
      { token: "function", foreground: "268bd2" },
      { token: "variable", foreground: "b58900" },
      { token: "namespace", foreground: "859900" },
      { token: "property", foreground: "268bd2" },
      { token: "operator", foreground: "93a1a1" },
      { token: "delimiter", foreground: "839496" },
      { token: "predefined", foreground: "268bd2" },
    ],
    appVars: {
      "--bg-main-color": "#002b36",
      "--bg-layer-color": "#073642",
      "--bg-hover-color": "#268bd222",
      "--bg-active-color": "#586e75",
      "--bg-focus-color": "#586e75",
      "--bg-thirt-color": "#073642",
      "--text-color": "#839496",
      "--text-primary-color": "#93a1a1",
      "--text-secondary-color": "#586e75",
      "--text-tertiary-color": "#839496",
      "--border-color": "#586e75",
      "--border-hard-color": "#93a1a1",
      "--border-component-style": "1px solid #586e75",
      "--focus-color": "#268bd2",
      "--btn-color": "#93a1a1",
      "--btn-secondary-color": "#073642",
      "--btn-secondary-text-color": "#268bd2",
      "--btn-secondary-focus-color": "#0a4050",
      "--btn-primary-bg": "#268bd2",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#0a4050",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#586e7570",
      "--scroll-thumb-hover-color": "#657b83",
      "--bg-tooltip-color": "#073642",
      "--bg-tooltip-border-color": "#586e75",
      "--tooltip-color": "#839496",
      "--trail-cursor-color": "#268bd2",
      "--checkbox-thumb-active-color": "#268bd2",
      "--td-slide-bg": "#268bd2",
      "--td-monaco-footer-bg": "#002b36",
      "--td-monaco-footer-fg": "#839496",
      "--td-monaco-text-active": "#839496",
      "--td-monaco-text-inactive": "#586e75",
      "--text-color-secondary": "#586e75",
      "--bg-secondary": "#073642",
      "--bg-color": "#002b36",
    },
  },
  {
    name: "one-light",
    label: "One Light",
    base: "vs",
    colors: {
      "editor.background": "#fafafa",
      "editor.foreground": "#383a42",
      "editor.lineHighlightBackground": "#eaeaeb",
      "editor.selectionBackground": "#e5e5e6",
      "editorCursor.foreground": "#526fff",
      "editorLineNumber.foreground": "#d0d0d0",
      "editorLineNumber.activeForeground": "#383a42",
      "editorBracketMatch.background": "#eaeaeb",
      "editorBracketMatch.border": "#383a42",
      "scrollbar.shadow": "#fafafa",
      "scrollbarSlider.background": "#d0d0d0",
      "scrollbarSlider.hoverBackground": "#b0b0b0",
      "scrollbarSlider.activeBackground": "#909090",
      "minimap.background": "#fafafa",
      "editorGutter.background": "#fafafa",
      "editorWidget.background": "#fafafa",
    },
    rules: [
      { token: "keyword", foreground: "a626a4" },
      { token: "string", foreground: "50a14f" },
      { token: "string.sql", foreground: "50a14f" },
      { token: "number", foreground: "986801" },
      { token: "comment", foreground: "a0a1a7" },
      { token: "type", foreground: "e45649" },
      { token: "function", foreground: "4078f2" },
      { token: "variable", foreground: "e45649" },
      { token: "namespace", foreground: "a626a4" },
      { token: "property", foreground: "4078f2" },
      { token: "operator", foreground: "383a42" },
      { token: "delimiter", foreground: "383a42" },
      { token: "predefined", foreground: "4078f2" },
    ],
    appVars: {
      "--bg-main-color": "#fafafa",
      "--bg-layer-color": "#e0e0e2",
      "--bg-hover-color": "#4078f220",
      "--bg-active-color": "#e5e5e6",
      "--bg-focus-color": "#e5e5e6",
      "--bg-thirt-color": "#eef0f2",
      "--text-color": "#383a42",
      "--text-primary-color": "#383a42",
      "--text-secondary-color": "#a0a1a7",
      "--text-tertiary-color": "#383a42",
      "--border-color": "#c4c4c8",
      "--border-hard-color": "#383a42",
      "--border-component-style": "1px solid #d0d0d0",
      "--focus-color": "#4078f2",
      "--btn-color": "#383a42",
      "--btn-secondary-color": "#eaeaeb",
      "--btn-secondary-text-color": "#4078f2",
      "--btn-secondary-focus-color": "#d8d8da",
      "--btn-primary-bg": "#4078f2",
      "--selected-item-text-color": "var(--btn-secondary-color)",
      "--btn-secondary-bg": "var(--btn-secondary-color)",
      "--btn-secondary-hover-bg": "var(--btn-secondary-focus-color)",
      "--btn-secondary-hover-border": "transparent",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#d0d0d0",
      "--scroll-thumb-hover-color": "#b0b0b0",
      "--bg-tooltip-color": "#eaeaeb",
      "--bg-tooltip-border-color": "#d0d0d0",
      "--tooltip-color": "#696d77",
      "--trail-cursor-color": "#383a42",
      "--checkbox-thumb-active-color": "#4078f2",
      "--td-slide-bg": "#4078f2",
      "--td-monaco-footer-bg": "#fafafa",
      "--td-monaco-footer-fg": "#383a42",
      "--td-monaco-text-active": "#383a42",
      "--td-monaco-text-inactive": "#a0a1a7",
      "--text-color-secondary": "#a0a1a7",
      "--bg-secondary": "#eaeaeb",
      "--bg-color": "#fafafa",
    },
  },
  {
    name: "one-dark",
    label: "One Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#282c34",
      "editor.foreground": "#abb2bf",
      "editor.lineHighlightBackground": "#2c323c",
      "editor.selectionBackground": "#3e4451",
      "editorCursor.foreground": "#528bff",
      "editorLineNumber.foreground": "#4b5263",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorBracketMatch.background": "#2c323c",
      "editorBracketMatch.border": "#528bff",
      "scrollbar.shadow": "#282c34",
      "scrollbarSlider.background": "#4b5263",
      "scrollbarSlider.hoverBackground": "#5c6370",
      "scrollbarSlider.activeBackground": "#6e7681",
      "minimap.background": "#282c34",
      "editorGutter.background": "#282c34",
      "editorWidget.background": "#2c323c",
    },
    rules: [
      { token: "keyword", foreground: "c678dd" },
      { token: "string", foreground: "98c379" },
      { token: "string.sql", foreground: "98c379" },
      { token: "number", foreground: "d19a66" },
      { token: "comment", foreground: "5c6370" },
      { token: "type", foreground: "e5c07b" },
      { token: "function", foreground: "61afef" },
      { token: "variable", foreground: "e5c07b" },
      { token: "namespace", foreground: "c678dd" },
      { token: "property", foreground: "61afef" },
      { token: "operator", foreground: "abb2bf" },
      { token: "delimiter", foreground: "abb2bf" },
      { token: "predefined", foreground: "61afef" },
    ],
    appVars: {
      "--bg-main-color": "#282c34",
      "--bg-layer-color": "#2c323c",
      "--bg-hover-color": "#61afef22",
      "--bg-active-color": "#3e4451",
      "--bg-focus-color": "#3e4451",
      "--bg-thirt-color": "#333842",
      "--text-color": "#abb2bf",
      "--text-primary-color": "#abb2bf",
      "--text-secondary-color": "#5c6370",
      "--text-tertiary-color": "#abb2bf",
      "--border-color": "#3e4451",
      "--border-hard-color": "#abb2bf",
      "--border-component-style": "1px solid #3e4451",
      "--focus-color": "#61afef",
      "--btn-color": "#abb2bf",
      "--btn-secondary-color": "#2c323c",
      "--btn-secondary-text-color": "#61afef",
      "--btn-secondary-focus-color": "#3a3f4b",
      "--btn-primary-bg": "#61afef",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#3a3f4b",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#4b526370",
      "--scroll-thumb-hover-color": "#5c6370",
      "--bg-tooltip-color": "#2c323c",
      "--bg-tooltip-border-color": "#3e4451",
      "--tooltip-color": "#abb2bf",
      "--trail-cursor-color": "#61afef",
      "--checkbox-thumb-active-color": "#61afef",
      "--td-slide-bg": "#61afef",
      "--td-monaco-footer-bg": "#282c34",
      "--td-monaco-footer-fg": "#abb2bf",
      "--td-monaco-text-active": "#abb2bf",
      "--td-monaco-text-inactive": "#5c6370",
      "--text-color-secondary": "#5c6370",
      "--bg-secondary": "#2c323c",
      "--bg-color": "#282c34",
    },
  },
  {
    name: "gruvbox-light",
    label: "Gruvbox Light",
    base: "vs",
    colors: {
      "editor.background": "#fbf1c7",
      "editor.foreground": "#3c3836",
      "editor.lineHighlightBackground": "#ebdbb2",
      "editor.selectionBackground": "#d5c4a1",
      "editorCursor.foreground": "#3c3836",
      "editorLineNumber.foreground": "#bdae93",
      "editorLineNumber.activeForeground": "#3c3836",
      "editorBracketMatch.background": "#ebdbb2",
      "editorBracketMatch.border": "#689d6a",
      "scrollbar.shadow": "#fbf1c7",
      "scrollbarSlider.background": "#bdae93",
      "scrollbarSlider.hoverBackground": "#a89984",
      "scrollbarSlider.activeBackground": "#928374",
      "minimap.background": "#fbf1c7",
      "editorGutter.background": "#fbf1c7",
      "editorWidget.background": "#fbf1c7",
    },
    rules: [
      { token: "keyword", foreground: "9d0006" },
      { token: "string", foreground: "79740e" },
      { token: "string.sql", foreground: "79740e" },
      { token: "number", foreground: "8f3f71" },
      { token: "comment", foreground: "bdae93" },
      { token: "type", foreground: "b57614" },
      { token: "function", foreground: "076678" },
      { token: "variable", foreground: "b57614" },
      { token: "namespace", foreground: "9d0006" },
      { token: "property", foreground: "076678" },
      { token: "operator", foreground: "3c3836" },
      { token: "delimiter", foreground: "3c3836" },
      { token: "predefined", foreground: "076678" },
    ],
    appVars: {
      "--bg-main-color": "#fbf1c7",
      "--bg-layer-color": "#ebdbb2",
      "--bg-hover-color": "#07667820",
      "--bg-active-color": "#d5c4a1",
      "--bg-focus-color": "#ebdbb2",
      "--bg-thirt-color": "#f4e8c1",
      "--text-color": "#3c3836",
      "--text-primary-color": "#3c3836",
      "--text-secondary-color": "#bdae93",
      "--text-tertiary-color": "#504945",
      "--border-color": "#c8b892",
      "--border-hard-color": "#3c3836",
      "--border-component-style": "1px solid #d5c4a1",
      "--focus-color": "#076678",
      "--btn-color": "#3c3836",
      "--btn-secondary-color": "#ebdbb2",
      "--btn-secondary-text-color": "#076678",
      "--btn-secondary-focus-color": "#d5c4a1",
      "--btn-primary-bg": "#076678",
      "--selected-item-text-color": "var(--btn-secondary-color)",
      "--btn-secondary-bg": "var(--btn-secondary-color)",
      "--btn-secondary-hover-bg": "var(--btn-secondary-focus-color)",
      "--btn-secondary-hover-border": "transparent",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#bdae9370",
      "--scroll-thumb-hover-color": "#a89984",
      "--bg-tooltip-color": "#ebdbb2",
      "--bg-tooltip-border-color": "#d5c4a1",
      "--tooltip-color": "#504945",
      "--trail-cursor-color": "#3c3836",
      "--checkbox-thumb-active-color": "#076678",
      "--td-slide-bg": "#076678",
      "--td-monaco-footer-bg": "#fbf1c7",
      "--td-monaco-footer-fg": "#3c3836",
      "--td-monaco-text-active": "#3c3836",
      "--td-monaco-text-inactive": "#bdae93",
      "--text-color-secondary": "#bdae93",
      "--bg-secondary": "#ebdbb2",
      "--bg-color": "#fbf1c7",
    },
  },
  {
    name: "gruvbox-dark",
    label: "Gruvbox Dark",
    base: "vs-dark",
    colors: {
      "editor.background": "#282828",
      "editor.foreground": "#ebdbb2",
      "editor.lineHighlightBackground": "#3c3836",
      "editor.selectionBackground": "#504945",
      "editorCursor.foreground": "#ebdbb2",
      "editorLineNumber.foreground": "#665c54",
      "editorLineNumber.activeForeground": "#ebdbb2",
      "editorBracketMatch.background": "#3c3836",
      "editorBracketMatch.border": "#689d6a",
      "scrollbar.shadow": "#282828",
      "scrollbarSlider.background": "#665c54",
      "scrollbarSlider.hoverBackground": "#7c6f64",
      "scrollbarSlider.activeBackground": "#928374",
      "minimap.background": "#282828",
      "editorGutter.background": "#282828",
      "editorWidget.background": "#3c3836",
    },
    rules: [
      { token: "keyword", foreground: "fb4934" },
      { token: "string", foreground: "b8bb26" },
      { token: "string.sql", foreground: "b8bb26" },
      { token: "number", foreground: "d3869b" },
      { token: "comment", foreground: "665c54" },
      { token: "type", foreground: "fabd2f" },
      { token: "function", foreground: "83a598" },
      { token: "variable", foreground: "fabd2f" },
      { token: "namespace", foreground: "fb4934" },
      { token: "property", foreground: "83a598" },
      { token: "operator", foreground: "ebdbb2" },
      { token: "delimiter", foreground: "ebdbb2" },
      { token: "predefined", foreground: "83a598" },
    ],
    appVars: {
      "--bg-main-color": "#282828",
      "--bg-layer-color": "#3c3836",
      "--bg-hover-color": "#83a59822",
      "--bg-active-color": "#504945",
      "--bg-focus-color": "#504945",
      "--bg-thirt-color": "#423b35",
      "--text-color": "#ebdbb2",
      "--text-primary-color": "#ebdbb2",
      "--text-secondary-color": "#665c54",
      "--text-tertiary-color": "#d5c4a1",
      "--border-color": "#504945",
      "--border-hard-color": "#ebdbb2",
      "--border-component-style": "1px solid #504945",
      "--focus-color": "#83a598",
      "--btn-color": "#ebdbb2",
      "--btn-secondary-color": "#3c3836",
      "--btn-secondary-text-color": "#83a598",
      "--btn-secondary-focus-color": "#4a4238",
      "--btn-primary-bg": "#83a598",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#4a4238",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#665c5470",
      "--scroll-thumb-hover-color": "#7c6f64",
      "--bg-tooltip-color": "#3c3836",
      "--bg-tooltip-border-color": "#504945",
      "--tooltip-color": "#ebdbb2",
      "--trail-cursor-color": "#83a598",
      "--checkbox-thumb-active-color": "#83a598",
      "--td-slide-bg": "#83a598",
      "--td-monaco-footer-bg": "#282828",
      "--td-monaco-footer-fg": "#ebdbb2",
      "--td-monaco-text-active": "#ebdbb2",
      "--td-monaco-text-inactive": "#665c54",
      "--text-color-secondary": "#665c54",
      "--bg-secondary": "#3c3836",
      "--bg-color": "#282828",
    },
  },
  {
    name: "catppuccin-light",
    label: "Catppuccin Latte",
    base: "vs",
    colors: {
      "editor.background": "#eff1f5",
      "editor.foreground": "#4c4f69",
      "editor.lineHighlightBackground": "#e6e9ef",
      "editor.selectionBackground": "#ccd0da",
      "editorCursor.foreground": "#dc8a78",
      "editorLineNumber.foreground": "#bcc0cc",
      "editorLineNumber.activeForeground": "#4c4f69",
      "editorBracketMatch.background": "#e6e9ef",
      "editorBracketMatch.border": "#40a02b",
      "scrollbar.shadow": "#eff1f5",
      "scrollbarSlider.background": "#bcc0cc",
      "scrollbarSlider.hoverBackground": "#9ca0b0",
      "scrollbarSlider.activeBackground": "#7c7f93",
      "minimap.background": "#eff1f5",
      "editorGutter.background": "#eff1f5",
      "editorWidget.background": "#eff1f5",
    },
    rules: [
      { token: "keyword", foreground: "8839ef" },
      { token: "string", foreground: "40a02b" },
      { token: "string.sql", foreground: "40a02b" },
      { token: "number", foreground: "fe640b" },
      { token: "comment", foreground: "bcc0cc" },
      { token: "type", foreground: "df8e1d" },
      { token: "function", foreground: "1e66f5" },
      { token: "variable", foreground: "df8e1d" },
      { token: "namespace", foreground: "8839ef" },
      { token: "property", foreground: "1e66f5" },
      { token: "operator", foreground: "4c4f69" },
      { token: "delimiter", foreground: "4c4f69" },
      { token: "predefined", foreground: "1e66f5" },
    ],
    appVars: {
      "--bg-main-color": "#eff1f5",
      "--bg-layer-color": "#dce0e8",
      "--bg-hover-color": "#1e66f520",
      "--bg-active-color": "#ccd0da",
      "--bg-focus-color": "#e6e9ef",
      "--bg-thirt-color": "#dce0e8",
      "--text-color": "#4c4f69",
      "--text-primary-color": "#4c4f69",
      "--text-secondary-color": "#9ca0b0",
      "--text-tertiary-color": "#5c5f77",
      "--border-color": "#bfc5d0",
      "--border-hard-color": "#4c4f69",
      "--border-component-style": "1px solid #ccd0da",
      "--focus-color": "#1e66f5",
      "--btn-color": "#4c4f69",
      "--btn-secondary-color": "#e6e9ef",
      "--btn-secondary-text-color": "#1e66f5",
      "--btn-secondary-focus-color": "#ccd0da",
      "--btn-primary-bg": "#1e66f5",
      "--selected-item-text-color": "var(--btn-secondary-color)",
      "--btn-secondary-bg": "var(--btn-secondary-color)",
      "--btn-secondary-hover-bg": "var(--btn-secondary-focus-color)",
      "--btn-secondary-hover-border": "transparent",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#bcc0cc",
      "--scroll-thumb-hover-color": "#9ca0b0",
      "--bg-tooltip-color": "#e6e9ef",
      "--bg-tooltip-border-color": "#ccd0da",
      "--tooltip-color": "#5c5f77",
      "--trail-cursor-color": "#4c4f69",
      "--checkbox-thumb-active-color": "#1e66f5",
      "--td-slide-bg": "#1e66f5",
      "--td-monaco-footer-bg": "#eff1f5",
      "--td-monaco-footer-fg": "#4c4f69",
      "--td-monaco-text-active": "#4c4f69",
      "--td-monaco-text-inactive": "#9ca0b0",
      "--text-color-secondary": "#9ca0b0",
      "--bg-secondary": "#e6e9ef",
      "--bg-color": "#eff1f5",
    },
  },
  {
    name: "catppuccin-dark",
    label: "Catppuccin Mocha",
    base: "vs-dark",
    colors: {
      "editor.background": "#1e1e2e",
      "editor.foreground": "#cdd6f4",
      "editor.lineHighlightBackground": "#313244",
      "editor.selectionBackground": "#45475a",
      "editorCursor.foreground": "#f5e0dc",
      "editorLineNumber.foreground": "#585b70",
      "editorLineNumber.activeForeground": "#cdd6f4",
      "editorBracketMatch.background": "#313244",
      "editorBracketMatch.border": "#a6e3a1",
      "scrollbar.shadow": "#1e1e2e",
      "scrollbarSlider.background": "#585b70",
      "scrollbarSlider.hoverBackground": "#6c7086",
      "scrollbarSlider.activeBackground": "#7f849c",
      "minimap.background": "#1e1e2e",
      "editorGutter.background": "#1e1e2e",
      "editorWidget.background": "#313244",
    },
    rules: [
      { token: "keyword", foreground: "cba6f7" },
      { token: "string", foreground: "a6e3a1" },
      { token: "string.sql", foreground: "a6e3a1" },
      { token: "number", foreground: "fab387" },
      { token: "comment", foreground: "585b70" },
      { token: "type", foreground: "f9e2af" },
      { token: "function", foreground: "89b4fa" },
      { token: "variable", foreground: "f9e2af" },
      { token: "namespace", foreground: "cba6f7" },
      { token: "property", foreground: "89b4fa" },
      { token: "operator", foreground: "#cdd6f4" },
      { token: "delimiter", foreground: "#cdd6f4" },
      { token: "predefined", foreground: "89b4fa" },
    ],
    appVars: {
      "--bg-main-color": "#1e1e2e",
      "--bg-layer-color": "#313244",
      "--bg-hover-color": "#89b4fa22",
      "--bg-active-color": "#45475a",
      "--bg-focus-color": "#45475a",
      "--bg-thirt-color": "#313244",
      "--text-color": "#cdd6f4",
      "--text-primary-color": "#cdd6f4",
      "--text-secondary-color": "#585b70",
      "--text-tertiary-color": "#bac2de",
      "--border-color": "#45475a",
      "--border-hard-color": "#cdd6f4",
      "--border-component-style": "1px solid #45475a",
      "--focus-color": "#89b4fa",
      "--btn-color": "#cdd6f4",
      "--btn-secondary-color": "#313244",
      "--btn-secondary-text-color": "#89b4fa",
      "--btn-secondary-focus-color": "#3b3d4f",
      "--btn-primary-bg": "#89b4fa",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#3b3d4f",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#585b7070",
      "--scroll-thumb-hover-color": "#6c7086",
      "--bg-tooltip-color": "#313244",
      "--bg-tooltip-border-color": "#45475a",
      "--tooltip-color": "#bac2de",
      "--trail-cursor-color": "#f5e0dc",
      "--checkbox-thumb-active-color": "#89b4fa",
      "--td-slide-bg": "#89b4fa",
      "--td-monaco-footer-bg": "#1e1e2e",
      "--td-monaco-footer-fg": "#cdd6f4",
      "--td-monaco-text-active": "#cdd6f4",
      "--td-monaco-text-inactive": "#585b70",
      "--text-color-secondary": "#585b70",
      "--bg-secondary": "#313244",
      "--bg-color": "#1e1e2e",
    },
  },
  {
    name: "monokai",
    label: "Monokai",
    base: "vs-dark",
    colors: {
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#3e3d32",
      "editor.selectionBackground": "#49483e",
      "editorCursor.foreground": "#f8f8f0",
      "editorLineNumber.foreground": "#75715e",
      "editorLineNumber.activeForeground": "#f8f8f2",
      "editorBracketMatch.background": "#3e3d32",
      "editorBracketMatch.border": "#a6e22e",
      "scrollbar.shadow": "#272822",
      "scrollbarSlider.background": "#75715e",
      "scrollbarSlider.hoverBackground": "#90908a",
      "scrollbarSlider.activeBackground": "#a6a69e",
      "minimap.background": "#272822",
      "editorGutter.background": "#272822",
      "editorWidget.background": "#3e3d32",
    },
    rules: [
      { token: "keyword", foreground: "f92672" },
      { token: "string", foreground: "e6db74" },
      { token: "string.sql", foreground: "e6db74" },
      { token: "number", foreground: "ae81ff" },
      { token: "comment", foreground: "75715e" },
      { token: "type", foreground: "a6e22e" },
      { token: "function", foreground: "a6e22e" },
      { token: "variable", foreground: "f8f8f2" },
      { token: "namespace", foreground: "f92672" },
      { token: "property", foreground: "66d9ef" },
      { token: "operator", foreground: "f92672" },
      { token: "delimiter", foreground: "f8f8f2" },
      { token: "predefined", foreground: "a6e22e" },
    ],
    appVars: {
      "--bg-main-color": "#272822",
      "--bg-layer-color": "#3e3d32",
      "--bg-hover-color": "#a6e22e22",
      "--bg-active-color": "#49483e",
      "--bg-focus-color": "#49483e",
      "--bg-thirt-color": "#3e3d32",
      "--text-color": "#f8f8f2",
      "--text-primary-color": "#f8f8f2",
      "--text-secondary-color": "#75715e",
      "--text-tertiary-color": "#f8f8f2",
      "--border-color": "#49483e",
      "--border-hard-color": "#f8f8f2",
      "--border-component-style": "1px solid #49483e",
      "--focus-color": "#a6e22e",
      "--btn-color": "#f8f8f2",
      "--btn-secondary-color": "#3e3d32",
      "--btn-secondary-text-color": "#66d9ef",
      "--btn-secondary-focus-color": "#4e4d42",
      "--btn-primary-bg": "#a6e22e",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#4e4d42",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#75715e70",
      "--scroll-thumb-hover-color": "#90908a",
      "--bg-tooltip-color": "#3e3d32",
      "--bg-tooltip-border-color": "#49483e",
      "--tooltip-color": "#f8f8f2",
      "--trail-cursor-color": "#a6e22e",
      "--checkbox-thumb-active-color": "#a6e22e",
      "--td-slide-bg": "#a6e22e",
      "--td-monaco-footer-bg": "#272822",
      "--td-monaco-footer-fg": "#f8f8f2",
      "--td-monaco-text-active": "#f8f8f2",
      "--td-monaco-text-inactive": "#75715e",
      "--text-color-secondary": "#75715e",
      "--bg-secondary": "#3e3d32",
      "--bg-color": "#272822",
    },
  },
  {
    name: "synthwave84",
    label: "Synthwave '84",
    base: "vs-dark",
    colors: {
      "editor.background": "#262335",
      "editor.foreground": "#b3b1ad",
      "editor.lineHighlightBackground": "#2a2739",
      "editor.selectionBackground": "#443b5b",
      "editorCursor.foreground": "#f92aad",
      "editorLineNumber.foreground": "#68647d",
      "editorLineNumber.activeForeground": "#f92aad",
      "editorBracketMatch.background": "#2a2739",
      "editorBracketMatch.border": "#fe4450",
      "scrollbar.shadow": "#262335",
      "scrollbarSlider.background": "#68647d66",
      "scrollbarSlider.hoverBackground": "#68647d",
      "scrollbarSlider.activeBackground": "#f92aad",
      "minimap.background": "#262335",
      "editorGutter.background": "#262335",
      "editorWidget.background": "#2a2739",
    },
    rules: [
      { token: "keyword", foreground: "fede5d" },
      { token: "string", foreground: "ff7edb" },
      { token: "string.sql", foreground: "ff7edb" },
      { token: "number", foreground: "f97e72" },
      { token: "comment", foreground: "848bbd" },
      { token: "type", foreground: "fe4450" },
      { token: "function", foreground: "36f9f6" },
      { token: "variable", foreground: "fede5d" },
      { token: "namespace", foreground: "fede5d" },
      { token: "property", foreground: "72f1b8" },
      { token: "operator", foreground: "36f9f6" },
      { token: "delimiter", foreground: "b3b1ad" },
      { token: "predefined", foreground: "36f9f6" },
    ],
    appVars: {
      "--bg-main-color": "#262335",
      "--bg-layer-color": "#2e2a40",
      "--bg-hover-color": "#36f9f622",
      "--bg-active-color": "#443b5b",
      "--bg-focus-color": "#443b5b",
      "--bg-thirt-color": "#2e2a40",
      "--text-color": "#b3b1ad",
      "--text-primary-color": "#b3b1ad",
      "--text-secondary-color": "#68647d",
      "--text-tertiary-color": "#b3b1ad",
      "--border-color": "#443b5b",
      "--border-hard-color": "#b3b1ad",
      "--border-component-style": "1px solid #443b5b",
      "--focus-color": "#36f9f6",
      "--btn-color": "#b3b1ad",
      "--btn-secondary-color": "#2a2739",
      "--btn-secondary-text-color": "#36f9f6",
      "--btn-secondary-focus-color": "#353248",
      "--btn-primary-bg": "#36f9f6",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#353248",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#68647d70",
      "--scroll-thumb-hover-color": "#68647d",
      "--bg-tooltip-color": "#2a2739",
      "--bg-tooltip-border-color": "#443b5b",
      "--tooltip-color": "#b3b1ad",
      "--trail-cursor-color": "#f92aad",
      "--checkbox-thumb-active-color": "#f92aad",
      "--td-slide-bg": "#36f9f6",
      "--td-monaco-footer-bg": "#262335",
      "--td-monaco-footer-fg": "#b3b1ad",
      "--td-monaco-text-active": "#f92aad",
      "--td-monaco-text-inactive": "#68647d",
      "--text-color-secondary": "#68647d",
      "--bg-secondary": "#2a2739",
      "--bg-color": "#262335",
    },
  },
  {
    name: "tokyo-night",
    label: "Tokyo Night",
    base: "vs-dark",
    colors: {
      "editor.background": "#1a1b26",
      "editor.foreground": "#a9b1d6",
      "editor.lineHighlightBackground": "#292e42",
      "editor.selectionBackground": "#343b58",
      "editorCursor.foreground": "#c0caf5",
      "editorLineNumber.foreground": "#3b4261",
      "editorLineNumber.activeForeground": "#73daca",
      "editorBracketMatch.background": "#292e42",
      "editorBracketMatch.border": "#bb9af7",
      "scrollbar.shadow": "#1a1b26",
      "scrollbarSlider.background": "#3b426166",
      "scrollbarSlider.hoverBackground": "#3b4261",
      "scrollbarSlider.activeBackground": "#343b58",
      "minimap.background": "#1a1b26",
      "editorGutter.background": "#1a1b26",
      "editorWidget.background": "#1f2335",
    },
    rules: [
      { token: "keyword", foreground: "bb9af7" },
      { token: "string", foreground: "9ece6a" },
      { token: "string.sql", foreground: "9ece6a" },
      { token: "number", foreground: "ff9e64" },
      { token: "comment", foreground: "565f89" },
      { token: "type", foreground: "2ac3de" },
      { token: "function", foreground: "7aa2f7" },
      { token: "variable", foreground: "c0caf5" },
      { token: "namespace", foreground: "bb9af7" },
      { token: "property", foreground: "7abc65" },
      { token: "operator", foreground: "89ddff" },
      { token: "delimiter", foreground: "a9b1d6" },
      { token: "predefined", foreground: "2ac3de" },
    ],
    appVars: {
      "--bg-main-color": "#1a1b26",
      "--bg-layer-color": "#24283b",
      "--bg-hover-color": "#7aa2f722",
      "--bg-active-color": "#343b58",
      "--bg-focus-color": "#343b58",
      "--bg-thirt-color": "#1f2335",
      "--text-color": "#a9b1d6",
      "--text-primary-color": "#c0caf5",
      "--text-secondary-color": "#565f89",
      "--text-tertiary-color": "#a9b1d6",
      "--border-color": "#343b58",
      "--border-hard-color": "#a9b1d6",
      "--border-component-style": "1px solid #343b58",
      "--focus-color": "#7aa2f7",
      "--btn-color": "#c0caf5",
      "--btn-secondary-color": "#1f2335",
      "--btn-secondary-text-color": "#7aa2f7",
      "--btn-secondary-focus-color": "#292e42",
      "--btn-primary-bg": "#7aa2f7",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#292e42",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#3b426170",
      "--scroll-thumb-hover-color": "#3b4261",
      "--bg-tooltip-color": "#1f2335",
      "--bg-tooltip-border-color": "#343b58",
      "--tooltip-color": "#a9b1d6",
      "--trail-cursor-color": "#c0caf5",
      "--checkbox-thumb-active-color": "#7aa2f7",
      "--td-slide-bg": "#7aa2f7",
      "--td-monaco-footer-bg": "#1a1b26",
      "--td-monaco-footer-fg": "#a9b1d6",
      "--td-monaco-text-active": "#73daca",
      "--td-monaco-text-inactive": "#565f89",
      "--text-color-secondary": "#565f89",
      "--bg-secondary": "#24283b",
      "--bg-color": "#1a1b26",
    },
  },
  {
    name: "dracula",
    label: "Dracula",
    base: "vs-dark",
    colors: {
      "editor.background": "#282a36",
      "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#44475a44",
      "editor.selectionBackground": "#44475a",
      "editorCursor.foreground": "#f8f8f0",
      "editorLineNumber.foreground": "#6272a4",
      "editorLineNumber.activeForeground": "#ff79c6",
      "editorBracketMatch.background": "#44475a",
      "editorBracketMatch.border": "#50fa7b",
      "scrollbar.shadow": "#282a36",
      "scrollbarSlider.background": "#6272a466",
      "scrollbarSlider.hoverBackground": "#6272a4",
      "scrollbarSlider.activeBackground": "#44475a",
      "minimap.background": "#282a36",
      "editorGutter.background": "#282a36",
      "editorWidget.background": "#21222c",
    },
    rules: [
      { token: "keyword", foreground: "ff79c6" },
      { token: "string", foreground: "f1fa8c" },
      { token: "string.sql", foreground: "f1fa8c" },
      { token: "number", foreground: "bd93f9" },
      { token: "comment", foreground: "6272a4" },
      { token: "type", foreground: "8be9fd" },
      { token: "function", foreground: "50fa7b" },
      { token: "variable", foreground: "f8f8f2" },
      { token: "namespace", foreground: "ff79c6" },
      { token: "property", foreground: "66d9ef" },
      { token: "operator", foreground: "ff79c6" },
      { token: "delimiter", foreground: "f8f8f2" },
      { token: "predefined", foreground: "8be9fd" },
    ],
    appVars: {
      "--bg-main-color": "#282a36",
      "--bg-layer-color": "#44475a",
      "--bg-hover-color": "#bd93f922",
      "--bg-active-color": "#6272a4",
      "--bg-focus-color": "#44475a",
      "--bg-thirt-color": "#21222c",
      "--text-color": "#f8f8f2",
      "--text-primary-color": "#f8f8f2",
      "--text-secondary-color": "#6272a4",
      "--text-tertiary-color": "#f8f8f2",
      "--border-color": "#6272a4",
      "--border-hard-color": "#f8f8f2",
      "--border-component-style": "1px solid #6272a4",
      "--focus-color": "#bd93f9",
      "--btn-color": "#f8f8f2",
      "--btn-secondary-color": "#44475a",
      "--btn-secondary-text-color": "#bd93f9",
      "--btn-secondary-focus-color": "#525577",
      "--btn-primary-bg": "#bd93f9",
      "--selected-item-text-color": "var(--bg-thirt-color)",
      "--btn-secondary-bg": "var(--bg-thirt-color)",
      "--btn-secondary-hover-bg": "#525577",
      "--btn-secondary-hover-border": "var(--border-color)",
      "--scroll-bg-color": "unset",
      "--scroll-thumb-color": "#6272a470",
      "--scroll-thumb-hover-color": "#6272a4",
      "--bg-tooltip-color": "#44475a",
      "--bg-tooltip-border-color": "#6272a4",
      "--tooltip-color": "#f8f8f2",
      "--trail-cursor-color": "#ff79c6",
      "--checkbox-thumb-active-color": "#bd93f9",
      "--td-slide-bg": "#bd93f9",
      "--td-monaco-footer-bg": "#282a36",
      "--td-monaco-footer-fg": "#f8f8f2",
      "--td-monaco-text-active": "#ff79c6",
      "--td-monaco-text-inactive": "#6272a4",
      "--text-color-secondary": "#6272a4",
      "--bg-secondary": "#44475a",
      "--bg-color": "#282a36",
    },
  },
];

export function registerAllMonacoThemes(monaco) {
  THEMES.forEach(function (t) {
    monaco.editor.defineTheme(t.name, {
      base: t.base,
      inherit: true,
      rules: t.rules,
      colors: t.colors,
    });
  });
}

export function getMonacoSyntaxRules(themeName) {
  var theme = THEMES.find(function (t) {
    return t.name === themeName;
  });
  return theme ? theme.rules : [];
}

export var monacoThemeList = THEMES.map(function (t) {
  return { label: t.label, value: t.name };
});

/**
 * Map tra màu bg/fg của từng Monaco theme.
 * Dùng để set CSS vars --td-monaco-footer-bg / --td-monaco-footer-fg lên :root bằng JS.
 */
export var monacoThemeColorMap = THEMES.reduce(function (map, t) {
  map[t.name] = {
    bg:
      t.colors["editor.background"] ||
      (t.base === "vs" ? "#ffffff" : "#1e1e1e"),
    fg:
      t.colors["editor.foreground"] ||
      (t.base === "vs" ? "#000000" : "#d4d4d4"),
    activeFg:
      t.colors["editorLineNumber.activeForeground"] ||
      t.colors["editor.foreground"] ||
      (t.base === "vs" ? "#000000" : "#d4d4d4"),
    inactiveFg:
      t.colors["editorLineNumber.foreground"] ||
      (t.base === "vs" ? "#8b949e" : "#636e7b"),
  };
  return map;
}, {});

/**
 * Lấy appVars (full CSS vars cho app) theo tên theme.
 * Trả về object { "--var-name": "value", ... } hoặc null nếu không tìm thấy.
 */
export function getAppVarsByTheme(themeName) {
  var theme = THEMES.find(function (t) {
    return t.name === themeName;
  });
  return theme ? theme.appVars : null;
}

/**
 * Lấy base type ("vs" hoặc "vs-dark") theo tên theme.
 * Dùng để xác định light/dark mode cho background effects.
 */
export function getThemeBase(themeName) {
  var theme = THEMES.find(function (t) {
    return t.name === themeName;
  });
  return theme ? theme.base : "vs";
}
